services:
  rag:
    build: ./project-1-rag-assistant
    ports:
      - "8010:8000"
    env_file:
      - ./project-1-rag-assistant/.env.example
      - ./project-1-rag-assistant/.env
    volumes:
      - chroma_cache:/root/.cache/chroma

  sql:
    build: ./project-2-sql-agent
    ports:
      - "8011:8001"
    env_file:
      - ./project-1-rag-assistant/.env.example
      - ./project-1-rag-assistant/.env
    depends_on:
      - rag

  jd:
    build: ./project-3-jd-match
    ports:
      - "8012:8002"
    env_file:
      - ./project-1-rag-assistant/.env.example
      - ./project-1-rag-assistant/.env

volumes:
  chroma_cache:
